name: Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: current dir display 
        run: pwd
        
      - name: change dir
        run: cd HelloWeb
        
      - name: current dir display 
        run: pwd
        
      - name: maven version display
        run: mvn --version
