name: Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install libraries
        run: |
          sudo apt update
          sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev
      - name: change dir
        run: cd HelloWeb
        
      - name: Make staging directory
        run: mkdir staging
        
      - name: Gluon Build
        run: mvn -Pdesktop gluonfx:build gluonfx:package

      - name: Copy native image to staging
        run: cp -r target/gluonfx/x86_64-linux/HelloGluon* staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
