name: Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: current dir display 
        run: pwd
        
      - name: change dir
        run: java --version
        
      - name: current dir display 
        run: ls
        
      - name: build
        run: mvn -f HelloWeb/pom.xml gluonfx:build 
