name: Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: set 
        run: pwd
        
      - name: Make staging directory
        run: mkdir staging
        
      - name: set GRAALVM_HOME env variable
        run: export GRAALVM_HOME=$GRAALVM_11_ROOT
        
      - name: build
        run: mvn -f HelloWeb/pom.xml gluonfx:build gluonfx:package -Pweb
      
      - name: Copy native image to staging
        run: cp -r target/gluonfx/x86_64-linux/HelloGluon* staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
